name: Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next version (eg. major, minor, patch)'
        default: 'patch'
        required: true
        type: string

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  update-version:
    name: Update version
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set git config user
        run:  |
          git config user.email "noreply@github.com"
          git config user.name "GitHub"
      - name: Update version
        run: npm version ${{ inputs.version }}
      - name: Push changes
        run: git push --follow-tags
